name: Build EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 根据您的项目需要选择Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole your_script.py  # 替换为您的脚本名

      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: Photooo-exe
          path: dist/POO.exe  # 替换为生成的exe文件名